import React from 'react';
import {DrawerNavigationProp} from '@react-navigation/drawer';
import {InformationScreen} from '../components/InformationSreen';

export interface TncProps {
  navigation: DrawerNavigationProp<any>;
}

const data = `These terms and conditions shall govern the use of the CallSpace Mobile application, Aapka Sarthi Website and application and the purchase of any services from it. The Website and application and application is owned and operated by Aapka Sarthi.

Please note that by accessing, using or browsing this Website and application you agree to be bound by these terms and conditions. CallSpace reserve the right to amend or update these terms and conditions at any time without providing notice. By using the Website and application, you acknowledge that you have read and understood these Terms and Conditions.

Should you have any questions, please Contact CallSpace at prior to purchasing and subscription or plan through this Website and application. Copyright in the Aapkasarthi.com Website and application is the property of CallSpace. The material on this Website and application also comprises copyright material, trademarks and registered trademarks which are the property of CallSpace and third parties. This property may only be used for the purposes of browsing the CallSpace Website and application and acquiring services of CallSpace.

You will need to read this Agreement in its entirety to review the general provisions of the Terms and conditions and Additional Terms specific to the product or service for which you are now signing up. Your use of CallSpace constitutes your agreement to these Terms and conditions. Your use of a particular CallSpace Web site included within, or acceptance of a product, service, or benefit obtained through CallSpace, may also be subject to additional terms specified in this document, on the applicable CallSpace Website and application or in other accompanying documentation (as such terms that may be modified by CallSpace from time to time as described below in the “Additional Terms”).

If any of the terms, conditions, and notices contained herein conflict with the Additional Terms or other terms and guidelines contained within or applicable to any particular CallSpace Web site, service, product or benefit, then the applicable Additional Terms shall control. You agree to familiarize yourself with the Terms and conditions and Notices, including the Additional Terms, and other terms and guidelines found throughout the CallSpace Web site and abide by them if you choose to use the sites, or accept the products, services or benefits, to which such terms apply.

You are required to agree to the following terms and conditions. Please read these terms and conditions carefully before purchasing any of CallSpace’s products and/or services on this Website and application.

To use any CallSpace Service, you must submit certain registration data. Such registration data shall include, but shall not be limited to, your name, address, e-mail address, phone number, and other billing information. You hereby certify that all of the registration data you provide to CallSpace is accurate and complete, and you agree to notify CallSpace within thirty (30) days of any changes to such data.

CallSpace reserves the right to modify this Agreement at its own discretion. If any modification to this Agreement is unacceptable to you, you may immediately terminate or cancel this agreement by providing written a notice to CallSpace; you will not receive any refund of fees paid by you hereunder in connection with any such termination. If you do not terminate or cancel the Agreement, or if you continue to use a Subscription Service or any other SERVICE following any modification to this Agreement, your continued use will mean that you have accepted that modification. You are responsible for regularly reviewing these terms and conditions.

Some products and services available through or in connection with CallSpace require that you purchase a Subscription Service or otherwise pay a fee and/or a monthly fee. Charges may apply for certain services such as, Website and application design, Website and application hosting, consulting, subscription services, or any other service as described on the CallSpace Website and application. You agree to pay CallSpace all amounts due upon demand. ​
​
The payments for subscriptions on the CallSpace Website and application are processed by
    ~ Zoho Subscriptions using Razorpay Payment Gateway
    ~ Paytm Gateway
    ~ Paypal  
​Payments that are overdue will accrue at the rate of 10% calculated daily from the due date, until paid in full to the Company. You must notify CallSpace in writing that you are terminating this Agreement, fees pre-paid by you to CallSpace for CallSpace products or services will not be credited back to your applicable credit card or otherwise refunded to you. CallSpace is not required to refund directly or indirectly to you any amounts paid hereunder. You understand that if CallSpace does not receive timely payment of all amounts due for any Subscription Service or any other Service you purchase, your use of all Services and Subscription Services may be severely restricted or terminated, at CallSpace’s sole discretion. You agree to pay any taxes, duties, and assessments arising out of your use of CallSpace. You agree to pay all attorney and collection fees arising from our efforts to collect any past due amounts from you to the extent allowed by law.

Links within CallSpace may let you leave CallSpace. You acknowledge that the linked sites are not under the control of CallSpace and that CallSpace is not responsible for the contents or operation of such linked sites or any link contained in such linked site, or any changes or updates to such sites. CallSpace is not responsible for webcasting or any other form of transmission received from any linked site. CallSpace is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by CallSpace of the linked site or any association with their operators.

CallSpace does not claim ownership of the materials you provide to CallSpace (including feedback and suggestions) or post, upload, input or submit in connection with your use of CallSpace or any web site (“Your Web Site”) created by CallSpace for you or on your behalf in connection with the use of CallSpace (collectively “Submissions”). However, you grant CallSpace a royalty-free license to use (including, without limitation, the rights to: copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate, sublicense and reformat your Submission, and to publish your Website and application name on the CallSpace Website and application as in a section called “Our Clients”) your Submission only in connection with the operation and promotion of CallSpace. No compensation will be paid or due you with respect to CallSpace's or its sublicensees use of the materials as licensed. CallSpace is under no obligation to post or use any materials you may provide, and may remove such materials at any time in CallSpace’s sole discretion. By posting messages, uploading files, inputting data, submitting any feedback or suggestions, or engaging in any other form of communication with or through any CallSpace Website and application, you warrant and represent that you own or otherwise control the rights necessary to do so and to grant CallSpace the license set forth above, and you will defend and indemnify CallSpace and its suppliers from any third party claim related to a breach of any of the foregoing representations or warranties.

You agree that our entire liability and that of any third party providing services as part of the subscription service or any other service, and your exclusive remedy, with respect to the subscription service and any other service, and any matter arising out of this agreement, is solely limited to the amount you paid for such subscription service or service. CallSpace, its contractors, affiliates (including third parties providing services as part of the subscription service or any other service) and parent companies shall not be liable for any direct, indirect, punitive, incidental, special, consequential or exemplary damages or any damages whatsoever including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of CallSpace or resulting from the use or inability to use the subscription service or any other service, or any of the CallSpace designed web sites, web site hosting service, or other CallSpace services or for the cost of procurement of substitute services. Because some states do not allow the exclusion or limitation of liability for consequential or incidental damages, in such states, our liability is limited to the extent permitted by law. We disclaim any and all loss or liability resulting from, but not limited to:
  Loss or liability resulting from access delays or access interruptions;
  Loss or liability resulting from data non-delivery or data mis-delivery;
  Loss or liability resulting from acts of god;
  Loss or liability resulting from the unauthorised use or misuse of your account information (including any passwords);
  Loss or liability resulting from errors, omissions, or misstatements in any and all information or service(s) provided under this agreement;
  Loss or liability relating to the deletion of or failure to store e-mail messages;
  Loss or liability resulting from the development or interruption of your CallSpace web site or any of the services included in the subscription service or any other service;
  Loss or liability from your inability to use any component of the subscription service or other services;
  Loss or liability that you may incur in connection with our processing of your application for our services, our processing of any authorised modification to your CallSpace Website and application or registration data, or your agent’s failure to pay any fees, including the monthly subscription service fee.
You hereby acknowledge that this provision will apply whether or not CallSpace is given notice of the possibility of such damages and that this provision will apply to all content, merchandise or services available through CallSpace. The terms of this Section will survive any termination or cancellation of this agreement. The information, products, services, and other material included in or available through CallSpace may not be complete, and may include inaccuracies or errors, and may also be modified or deleted from time to time. Advice, information, products, services or other materials received via CallSpace should not be relied upon for personal, medical, legal, business, financial or other decisions and is not intended to replace the advice of appropriate and qualified professionals. You acknowledge that you should consult an appropriate professional for specific advice tailored to your situation. The terms of this Section will survive any termination or cancellation of this agreement. Without limiting the foregoing, CallSpace is not responsible for any of your data residing on CallSpace hardware. You are responsible for backing-up your data and information that may reside on the CallSpace hardware, or any 3rd party hardware, whether or not such information is produced through the use of CallSpace. It is your responsibility to take the necessary steps to ensure your primary means of business is maintained. The terms of this Section will survive any termination or cancellation of this agreement.

You agree and understand that you are using any Subscription Service or any other Service at your own risk. The Subscription Service or any other Service is provided on an AS IS, AS AVAILABLE BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. CallSpace Expressly DISCLAIMS any representation or warranty that the subscription Service or any other service will meet your requirements, be error-free, secure or uninterrupted. CallSpace does not guarantee your receipt of service at any particular time or the integrity of data stored or transmitted via its system. No oral advice or written information given by CallSpace, Its Employees, Licensors or the like, will create a Warranty; Nor may you rely on any such information or Advice. The terms of this Section will survive any termination or cancellation of this agreement.

CallSpace reserves the right to deny in its sole discretion any user access to CallSpace or any portion thereof without notice. You are responsible for safeguarding the confidentiality of your password(s) and username(s) issued to you by CallSpace, and for any use or misuse of your account or CallSpace resulting from any third party using a password or user name issued to you.

CallSpace may terminate this Agreement and your access to CallSpace (in whole or in part) and related services at any time, with or without cause, and with or without notice. Anyone determined by CallSpace to have violated these Terms and conditions and Notices, or any Additional Terms may be barred from using CallSpace, or from receiving any products, services or benefits from CallSpace. In addition, if you violate any of these Terms and conditions and Notices, or Additional Terms (as applicable) you will forfeit all in-kind credits and any other amounts accruing to you (if any) in connection with CallSpace.
    ~ Cancellation Policy
All fees are non-refundable once your request for a CallSpace Designed Website and application, a Subscription Service, the Website and application Hosting Service, or any Service is received. If you cancel your subscription before the end of any initial minimum term, CallSpace will not refund any subscription fees or payments for the customised Website and application development service paid prior to such cancellation. You will also be required to pay the entire standard monthly charge for each month remaining in any initial minimum term. To cancel your CallSpace subscription, you must submit your request for termination to CallSpace. For security reasons, all requests for cancellation of a subscription must be made by the primary contact person on the account and must specify the exact Service to be canceled and the applicable registered login email address for the account. Subscription cancellations will be effective upon CallSpace’s receipt of such information. Cancellation of any CallSpace service (whether by CallSpace or by you) will not relieve you of any payment obligations as set forth in these Terms and conditions and Notices.
    ~ Effect of Termination
Upon any termination of this Agreement, your right to use the Subscription Service (and, therefore, your license to use the CallSpace Website and application) or any other Service will automatically terminate, and you shall immediately cease any use of the CallSpace Website and application and the Subscription Service or any other Service; CallSpace shall immediately cease providing the Subscription Service or any other Service. Unless otherwise specified in writing by CallSpace, you will not receive any refund for monthly payments already made by you as of the date of termination. If termination of this Agreement is due to your default hereunder, you shall bear all costs of such termination, including any reasonable costs CallSpace incurs in closing your account. You agree to pay any and all costs incurred by CallSpace in enforcing compliance with this Section.
This agreement constitutes the entire agreement between you and CallSpace with respect to any Subscription Service or any other Service and your use of CallSpace supersedes all prior agreements between you and CallSpace pertaining to the same. CallSpace’s failure to enforce any provision of this agreement will not be construed as a waiver of any provision or right. In the event that a portion of this agreement is held unenforceable, the unenforceable portion will be construed in accordance with applicable law as nearly as possible to reflect the original intentions of the parties, and the remainder of the provisions will remain in full force and effect. Interpretation and enforcement of this agreement will be governed by the laws of the State of Delhi, India (excluding its choice of law rules). You hereby consent to personal jurisdiction in the federal courts in the district of the State of Delhi (New Delhi), Delhi for any action arising out of or related in any way to this Agreement or relating to your use of CallSpace (or any component thereof). Nothing in this agreement will be construed as creating a joint venture, partnership, employment or agency relationship between you and CallSpace, and you do not have any authority to create any obligation or make any representation on CallSpace’s behalf, unless a specific written agreement between you and CallSpace is made. Other than as specified herein, neither party makes any representations, or assumes or creates any obligations, on behalf of the other. You may not assign this agreement, by operation of law or otherwise, without alley’s written consent. Subject to the foregoing, this agreement will be binding on, inure to the benefit of and be enforceable against you and CallSpace and their respective successors and assigns. Other than services provided as a part of the Subscription Service or any other CallSpace Service, CallSpace is not responsible for and shall have no liability with respect to any products and/or services purchased by you from other parties, whether through the CallSpace Website and application or otherwise, and the provision of any such other products and/or services shall be subject to your agreement, if any, with the party providing the other products and/or services. The terms of this Section will survive any termination of this agreement.

You agree to defend, indemnify, and hold CallSpace and its contractors, agents, employees, officers, directors, shareholders, affiliates and assigns harmless from and against any and all claims, liabilities, damages, costs and expenses (including reasonable attorneys’ fees and expenses) of third parties arising from or related to
    ~ Any information, material, content products, or services available on your licensed CallSpace Designed Website and application;
    ~ Your use of the Website and application Hosting Service or the licensed CallSpace Designed Website and application, or any other Service; or
    ~ Any use of your licensed CallSpace Designed Website and application. The obligations in this Section will not be limited in any way by any other provisions of this Agreement, including the limitation of liability section set forth above.

 
    ~ You may cancel your account at anytime by emailing support@getCallSpace.com
    ~ Once your account is cancelled all of your content will be immediately deleted from the panels. Since deletion of all data is final please be sure that you do in fact want to cancel your account before doing so.
    ~ If you cancel the Service in the middle of the month, you will receive one final invoice via email. Once that invoice has been paid you will not be charged again.
    ~ Fraud: Without limiting any other remedies, CALLSPACE may suspend or terminate your account if we suspect that you (by conviction, settlement, insurance or escrow investigation, or otherwise) have engaged in fraudulent activity in connection with the Site.
Note: No refunds are offered, even if a plan is canceled mid-month.

Without limiting its other remedies, CallSpace may immediately issue a warning, temporarily suspend, indefinitely suspend or immediately terminate this Agreement and Your access to the Panel if You fail to comply with any terms specified herein. CallSpace may take such actions without providing You prior notice and at its sole discretion.

CallSpace reserves the right, in its sole and exclusive discretion, to suspend or terminate Services to You upon receipt of any third party complaint that You have engaged in any activity that violates this Agreement, which may otherwise subject CallSpace to liability for any reason, or that may cause CallSpace to incur legal fees or other expenses.

Upon termination, those provisions of this Agreement that expressly or by their nature survive will continue in full force and effect.
I have read all the terms & conditions mentioned above and I agree to abide by them.`;

export function Tnc({navigation}: TncProps) {
  return (
    <InformationScreen
      navigation={navigation}
      heading="Terms and Conditions"
      data={data}
    />
  );
}
